apiVersion: apps/v1
kind: Deployment
metadata:
  name: candy-v2
  namespace: canary-ns
  labels:
    app: candy
    version: v2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: candy
      version: v2
  template:
    metadata:
      labels:
        app: candy
        version: v2
    spec:
      containers:
      - name: candy
        image: samirsadek123/k8deploment:v2
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"