apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: candy-blue
  name: candy-blue
  namespace: blue-green-ns
spec:
  replicas: 4
  selector:
    matchLabels:
      app: candy-blue
  template:
    metadata:
      labels:
        app: candy-blue
    spec:
      containers:
      - image: samirsadek123/k8deploment:v1
        name: candy-blue
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: candy-blue-deployment-service
  namespace: blue-green-ns
spec:
  selector:
    app: candy-blue
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30001