apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: candy-shop
  name: candy-shop
  namespace: rolling-ns
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1             # Optional - 1 extra Pod can be created during update
      maxUnavailable: 0       # Optional - 0 unavailable Pods ensure 0 Downtime
  selector:
    matchLabels:
      app: candy-shop
  template:
    metadata:
      labels:
        app: candy-shop
    spec:
      containers:
      - name: candy-shop
        image: samirsadek123/k8deploment
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"